/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include "math.h"

void calculadora_1(char *host, double numIzquierda, char operacion, double numDerecha)
{
	CLIENT *clnt;
	double *resultado;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA, CALCULADORAV1, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	if (operacion == '+')
		resultado = suma_1(numIzquierda, numDerecha, clnt);
	else if (operacion == '-')
		resultado = resta_1(numIzquierda, numDerecha, clnt);
	else if (operacion == '*')
		resultado = multiplicacion_1(numIzquierda, numDerecha, clnt);
	else if (operacion == '/')
		resultado = division_1(numIzquierda, numDerecha, clnt);
	else
		fprintf(stderr, "Operador incorrecto. Introduzca una operación válida: +, -, *, / \n");

	if (resultado == (double *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}

	if (numDerecha == 0.0 && operacion == '/')
	{
		printf("%f %c %f = INDETERMINACION\n", numIzquierda, operacion, numDerecha);
	}
	else if (operacion == '+' || operacion == '-' || operacion == '*' || operacion == '/')
		printf("%f %c %f = %f\n", numIzquierda, operacion, numDerecha, *resultado);

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */

	
}

vect calculadora_vectores(char *host, vect vector1, char operacion, vect vector2){
	CLIENT *clnt;
	vect *resultado;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA, CALCULADORAV1, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */
	if (vector1.vect_len != vector2.vect_len)
		clnt_perror(clnt, "\nAmbos vectores deben tener la misma longitud");
	else {
		if (operacion == '+')
			resultado = sumavectores_1(vector1,vector2,clnt);
		else if (operacion == '-')
			resultado = restavectores_1(vector1,vector2,clnt);
		else if (operacion == '*')
			resultado = productovectores_1(vector1, vector2, clnt);
		else if (operacion == '/')
			resultado = divisionvectores_1(vector1, vector2, clnt);
		else if (operacion == '_')
			resultado = productoescalar_1(vector1, vector2, clnt);
		else
			fprintf(stderr, "Operador incorrecto. Introduzca una operación válida: +, -, *, /, | (producto escalar) \n");
	}

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */

	return *resultado;
}

ecuacionCuadrada calculadora_ecuacion_cuadratica(char *host, double a, double b, double c)
{
	CLIENT *clnt;
	ecuacionCuadrada *resultado;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA, CALCULADORAV1, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */
	
	resultado = cuadratica_1(a, b, c, clnt);

#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */

	ecuacionCuadrada result = *resultado;
	return result;
}

int
main (int argc, char *argv[])
{
	char *host;
	double numIzquierda, numDerecha;
	char operacion;
	double resultado;
	int numArray = 0; 
	double aux = 0;
	char op[1];
	vect vector1, vector2, resVec;
	ecuacionCuadrada resEcuacion;
	double a = 0, b = 0, c = 0;

	if (argc == 5)
	{
		host = argv[1];

		numDerecha = atoi(argv[4]) * 1.0;
		numIzquierda = atoi(argv[2]) * 1.0;
		operacion = *argv[3];
		calculadora_1(host, numIzquierda, operacion, numDerecha);

	} else if (argc == 3 && strcmp(argv[2], "vector") == 0){
		host = argv[1];
		printf("\nIntroduzca la longitud del vector: ");
		scanf("%d", &numArray);
		vector1.vect_len = vector2.vect_len = numArray;

		vector1.vect_val = malloc(vector1.vect_len * sizeof(double));
		vector2.vect_val = malloc(vector2.vect_len * sizeof(double));
		printf("\nIntroduzca el primer vector: ");

		for (int i = 0; i < numArray; i++){
			scanf("%lf", &aux);
			vector1.vect_val[i] = aux;
		}
		printf("\nIntroduzca la operacion a realizar: ");
		scanf(" %c", &operacion);
		
		printf("\nIntroduzca el segundo vector: ");
		for (int i = 0; i < numArray; i++)
		{
			scanf("%lf", &aux);
			vector2.vect_val[i] = aux;
		}

		resVec = calculadora_vectores(host,vector1,operacion, vector2);

		printf("["); 
		for (int i = 0; i < numArray; i++)
			printf(" %f ", resVec.vect_val[i]);
		printf("]");

		vector1.vect_len = 0; vector2.vect_len = 0; resVec.vect_len = 0;
		free(vector1.vect_val); free(vector2.vect_val); free(resVec.vect_val);

	} else if (argc == 6 && strcmp(argv[2], "ecuacion") == 0){
		printf("ax² + bx + c = 0");
		host = argv[1];
		a = atoi(argv[3]);
		b = atoi(argv[4]);
		c = atoi(argv[5]);
		
		resEcuacion = calculadora_ecuacion_cuadratica(host,a,b,c);

		if (resEcuacion.res1 != INT_MIN)
			printf("\nLos resultados de la ecuacion de segundo grado son: %lf , %lf\n", resEcuacion.res1, resEcuacion.res2);
	} else {
		printf("\n\n %s ", *argv[3]);
		printf("usage: <server> <entero> <operacion> <entero>\n", argv[0]);
		exit(1);
	}
	
	exit(0);
}
