/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static double *
_suma_1 (suma_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_resta_1 (resta_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_multiplicacion_1 (multiplicacion_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicacion_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_division_1 (division_1_argument *argp, struct svc_req *rqstp)
{
	return (division_1_svc(argp->arg1, argp->arg2, rqstp));
}

static ecuacionCuadrada *
_cuadratica_1 (cuadratica_1_argument *argp, struct svc_req *rqstp)
{
	return (cuadratica_1_svc(argp->arg1, argp->arg2, argp->arg3, rqstp));
}

static vect *
_sumavectores_1 (sumavectores_1_argument *argp, struct svc_req *rqstp)
{
	return (sumavectores_1_svc(argp->arg1, argp->arg2, rqstp));
}

static vect *
_restavectores_1 (restavectores_1_argument *argp, struct svc_req *rqstp)
{
	return (restavectores_1_svc(argp->arg1, argp->arg2, rqstp));
}

static vect *
_productovectores_1 (productovectores_1_argument *argp, struct svc_req *rqstp)
{
	return (productovectores_1_svc(argp->arg1, argp->arg2, rqstp));
}

static vect *
_divisionvectores_1 (divisionvectores_1_argument *argp, struct svc_req *rqstp)
{
	return (divisionvectores_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_productoescalar_1 (productoescalar_1_argument *argp, struct svc_req *rqstp)
{
	return (productoescalar_1_svc(argp->arg1, argp->arg2, rqstp));
}

static void
calculadora_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_1_argument suma_1_arg;
		resta_1_argument resta_1_arg;
		multiplicacion_1_argument multiplicacion_1_arg;
		division_1_argument division_1_arg;
		cuadratica_1_argument cuadratica_1_arg;
		sumavectores_1_argument sumavectores_1_arg;
		restavectores_1_argument restavectores_1_arg;
		productovectores_1_argument productovectores_1_arg;
		divisionvectores_1_argument divisionvectores_1_arg;
		productoescalar_1_argument productoescalar_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA:
		_xdr_argument = (xdrproc_t) xdr_suma_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case RESTA:
		_xdr_argument = (xdrproc_t) xdr_resta_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case MULTIPLICACION:
		_xdr_argument = (xdrproc_t) xdr_multiplicacion_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _multiplicacion_1;
		break;

	case DIVISION:
		_xdr_argument = (xdrproc_t) xdr_division_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _division_1;
		break;

	case CUADRATICA:
		_xdr_argument = (xdrproc_t) xdr_cuadratica_1_argument;
		_xdr_result = (xdrproc_t) xdr_ecuacionCuadrada;
		local = (char *(*)(char *, struct svc_req *)) _cuadratica_1;
		break;

	case SUMAVECTORES:
		_xdr_argument = (xdrproc_t) xdr_sumavectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_vect;
		local = (char *(*)(char *, struct svc_req *)) _sumavectores_1;
		break;

	case RESTAVECTORES:
		_xdr_argument = (xdrproc_t) xdr_restavectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_vect;
		local = (char *(*)(char *, struct svc_req *)) _restavectores_1;
		break;

	case PRODUCTOVECTORES:
		_xdr_argument = (xdrproc_t) xdr_productovectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_vect;
		local = (char *(*)(char *, struct svc_req *)) _productovectores_1;
		break;

	case DIVISIONVECTORES:
		_xdr_argument = (xdrproc_t) xdr_divisionvectores_1_argument;
		_xdr_result = (xdrproc_t) xdr_vect;
		local = (char *(*)(char *, struct svc_req *)) _divisionvectores_1;
		break;

	case PRODUCTOESCALAR:
		_xdr_argument = (xdrproc_t) xdr_productoescalar_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _productoescalar_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA, CALCULADORAV1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORAV1, calculadora_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORAV1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, CALCULADORAV1, calculadora_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, CALCULADORAV1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
